# Generated by Django 2.2.1 on 2019-06-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0005_ucenik_godina_upisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
